# Generated by Django 3.2.4 on 2021-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/532dfdbcc6479placeholder_food_item_2.png', max_length=600),
        ),
    ]
